name: auto_build

on:
    push:
        branches:
            - master
jobs:
    build_job:
        name: auto_build_job
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@master
            - name: install-dependencies
              run: |
                sudo apt-get update
                sudo apt-get install wget tar build-essential -y
            - name: build-package
              run: |
                wget https://sourceforge.net/projects/asio/files/asio/1.16.1%20%28Stable%29/asio-1.16.1.tar.gz/download -O asio-1.16.1.tar.gz
                tar -zxvf  asio-1.16.1.tar.gz
                cd asio-1.16.1
                ./configure
                make -j$(nproc)
            - name: pack-executable
              run: |
                tar zcvf cpp11.tar.gz asio-1.16.1/src/examples/cpp11
            - name: download-executable
              uses: actions/upload-artifact@master
              with:
                name: cpp11
                path: cpp11.tar.gz
            
    
